export default {
  html: `<div class="work-item-tag" style="background: #80bf99; border: 1px solid #7C8594; color: #7C8594">HTML</div>`,
  css: `<div class="work-item-tag" style="background: #4785b8; border: 1px solid #7C8594; color: #7C8594">CSS</div>`,
  javascript: `<div class="work-item-tag" style="background: #FFB800;">JavaScript</div>`,
  socketio: `<div class="work-item-tag" style="background: #21BAEB;">Socket.IO</div>`,
  webgl: `<div class="work-item-tag" style="background: #5A69EC;">WebGL</div>`,
  api: `<div class="work-item-tag" style="background: #CA49F8;">API</div>`,
  VR: `<div class="work-item-tag" style="background: #8433CC;">VR</div>`,
  React: `<div class="work-item-tag" style="background: #1affa3;">React</div>`,
  Nodejs: `<div class="work-item-tag" style="background: #ff9933;">Node.js</div>`,
  TailwindCSS: `<div class="work-item-tag" style="background: #ff33ff;">Tailwind CSS</div>`,
  Nuxt: `<div class="work-item-tag" style="background: #7accd6;">Nuxt</div>`,
  Next: `<div class="work-item-tag" style="background: #f2f29e;">Next</div>`,
  Solidity: `<div class="work-item-tag" style="background: #8cffbf;">Solidity</div>`,
  Wordpress: `<div class="work-item-tag" style="background: #1a8ce6;">Wordpress</div>`,
  Mysql: `<div class="work-item-tag" style="background: #f2076e;">Mysql</div>`,
  Jquery: `<div class="work-item-tag" style="background: #7a33f0;">Jquery</div>`,
  Laravel: `<div class="work-item-tag" style="background: #6beb75;">Laravel</div>`,
  Django: `<div class="work-item-tag" style="background: #7da3ab;">Django</div>`,
  Vue: `<div class="work-item-tag" style="background: #eb2999;">Vue</div>`,
  Web3: `<div class="work-item-tag" style="background: #85d147;">Web3</div>`,
};
